### ISSUE TITLE
[Wiki] Class Loader

### ISSUE THREAD

**Issue by dongseop-lee** [scottSeo/scottseo.github.io#1]
http://epicdevs.com/16
읽어보기

**Comment by scottSeo** [comment]
기본적인 JAVA 에서는 Parent-First, Child-Last 지만,
WAS(일단 Tomcat)에서는 Parent-Last, Child-First 이다.
Class Loader 의 계층 구조에서 위임되는 순서가 꼭 정해져 있다고 볼 수는 없을 것 같다. WAS 에 따라 다르기도 하고, 설정에 따라 다를 수도 있는 듯. 
그렇게 알아두자.
