### ISSUE TITLE
[TIL] 2017-10-08

### ISSUE THREAD

**Issue by dongseop-lee** [scottSeo/scottseo.github.io#2]
@ResponseBody시 동작 원리를 알아 봐야 할 듯 합니다.
내부적으로 어떻게 동작하는지, JSON만 되는 것인지?
어떤 빈이 등록되어 있는 것인지 등등.

**Comment by scottSeo** [comment]
스프링 코드를 좀 뜯어보다보면 등록되어 있는 리졸버(?)에 따라 달랐던 것 같은데 한번 찾아보고 더 정확하게 정리해둘 필요가 있겠군요.

**Comment by scottSeo** [comment]
HTTP 요청의 단순 String 을 Java에 맞게 타입 변환 시키는 과정에서 Converter 가 사용되는데... 이와 동일하게.
ResponseBody를 보낼 때도 Converter 가 사용됩니다. 즉, JSON 뿐 아니라 Converter 가 존재하는 모든 경우에 동일하게 처리될 수 있습니다. 
https://github.com/scottSeo/scottseo.github.io/blob/master/til/20171008.md
