### ISSUE TITLE
[Wiki] Garbage Collections & Collectors

### ISSUE THREAD

**Issue by dongseop-lee** [scottSeo/scottseo.github.io#3]
http://linux.systemv.pe.kr/gc-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/
http://kh66attic.tistory.com/entry/JVM-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%EA%B0%80%EB%B9%84%EC%A7%80-%EC%BB%AC%EB%A0%89%EC%85%98Garbage-Collection-2-%EB%8F%99%EC%9E%91%EC%9B%90%EB%A6%AC
위 읽어보기.

**Comment by scottSeo** [comment]
접수완료.
